const TOUR_CODE_OVERRIDES_OPTION = {
  REPLACE_WITH_BT: "REPLACE_WITH_BT",
  REPLACE_WITH_IT: "REPLACE_WITH_IT",
  SUPPRESS_IT: "SUPPRESS_IT",
  SUPPRESS_IT_AND_FARE: "SUPPRESS_IT_AND_FARE"
} as const

export type TourCodeOverridesOptionEnum = keyof typeof TOUR_CODE_OVERRIDES_OPTION;