/**
 * Identifica el tipo de documento de pasajero.
 */
const DOCUMENT_TYPE = {
  PASSPORT: "PASSPORT",
  VISA: "VISA",
  SECURE_FLIGHT_PASSENGER_DATA: "SECURE_FLIGHT_PASSENGER_DATA",
  RESIDENCE_ADDRESS: "RESIDENCE_ADDRESS",
  DESTINATION_ADDRESS: "DESTINATION_ADDRESS",
  KNOWN_TRAVELER_NUMBER: "KNOWN_TRAVELER_NUMBER",
  REDRESS_NUMBER: "REDRESS_NUMBER",
  ALIEN_RESIDENT: "ALIEN_RESIDENT",
  PERMANENT_RESIDENT: "PERMANENT_RESIDENT",
  FACILITATION_DOCUMENT: "FACILITATION_DOCUMENT",
  NATIONAL_ID_CARD: "NATIONAL_ID_CARD",
  NEXUS_CARD: "NEXUS_CARD",
  MILITARY: "MILITARY",
  NATURALIZATION_CERTIFICATE: "NATURALIZATION_CERTIFICATE",
  REFUGEE_REENTRY_PERMIT: "REFUGEE_REENTRY_PERMIT",
  BORDER_CROSSING_CARD: "BORDER_CROSSING_CARD",
} as const

export type DocumentTypeEnum = keyof typeof DOCUMENT_TYPE;