/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Use this endpoint if you want to create an ATK token with an EPR. */
        post: operations["atkWithClientCredentialsAndId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Successful response */
        CreateSuccessful: {
            /**
             * @description The ATK lightweight token.
             * @example T1RLAQJPQzjC8M7MPu+2vm9J86MWvDzJIxBrkd3OsIZH9jSJ+Gbd15XoAACgsBW7lZMgx26vSTP4nx7E3Oa4Gpd2ypySwCFrtTCIp8YT3W/2lergfTRZsH2rUfGzQjz2SvMPoi20pvDMKkcgiju1DBrByskZg9gECjTXvI38gxKOyS4RmxOn4YJLXUSlzeKslMev0P8jmkg5wuQbyQIBHhISRKk0c8+0lW5lJfX0fueROpqx9oQMNdwcdMcrmvcA3eV+FkTCyJUgk3rT+w**
             */
            access_token: string;
            /**
             * @description The token type.
             * @example bearer
             */
            token_type: string;
            /**
             * @description The time of expiration in seconds.
             * @example 604800
             */
            expires_in: number;
        };
        /** Missing grant type */
        MissingGrantType: {
            /**
             * @description Error message.
             * @example invalid_request
             */
            error: string;
            /**
             * @description The grant type is not specified in the payload.
             * @example Invalid payload: grant_type must be specified
             */
            error_description: string;
        };
        /** Invalid grant type */
        InvalidGrantType: {
            /**
             * @description Error message.
             * @example invalid_request
             */
            error: string;
            /**
             * @description A grant type that was not supported was sent.
             * @example Invalid grant type. The only supported type is 'client_credentials'
             */
            error_description: string;
        };
        /** Invalid grant type */
        InvalidMethod: {
            /**
             * @description Error message.
             * @example invalid_request
             */
            error: string;
            /**
             * @description Invalid method. Only the POST method is available.
             * @example HTTP method not allowed
             */
            error_description: string;
        };
        /** Invalid grant type */
        InvalidContentType: {
            /**
             * @description Error message.
             * @example invalid_request
             */
            error: string;
            /**
             * @description Invalid `Content-Type`. Only application/x-www-form-urlencoded is valid.
             * @example Incorrect Content-Type. Only application/x-www-form-urlencoded is allowed
             */
            error_description: string;
        };
        /** Authentication failed */
        AuthenticationFailed: {
            /**
             * @description Error message.
             * @example invalid_client
             */
            error: string;
            /**
             * @description User's EPR authentication against security systems failed.
             * @example Wrong clientID or clientSecret
             */
            error_description: string;
        };
        /** Authentication data missing */
        MissingCredentials: {
            /**
             * @description Error message.
             * @example invalid_client
             */
            error: string;
            /**
             * @description Security data was not present in the request or are invalid e.g. credentials are encoded wrong.
             * @example Credentials are missing or the syntax is not correct
             */
            error_description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    atkWithClientCredentialsAndId: {
        parameters: {
            query?: never;
            header: {
                /** @description The word "Basic" followed by a base64 encoded EPR as base64(base64(V1:user:group:domain):base64(password)) pair e.g. Basic VmpFNmRYTmxjbWxrT21keWIzVndPbVJ2YldGcGJnPT06TVRJek5EVT0= */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /**
                     * @description The grant type used to obtain the token. Only "client_credentials" supported.
                     * @enum {string}
                     */
                    grant_type: "client_credentials";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSuccessful"];
                };
            };
            /** @description Either the clientId or the user's EPR authentication failed. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationFailed"];
                };
            };
        };
    };
}
